--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue
from customer group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 



SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased , ROUND(avg(review_rating::numeric),2) as avg_review_rating
from customer
group by item_purchased
order by avg_review_rating desc
limit 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 


select shipping_type, ROUND(AVG(purchase_amount),2) as "Avarage Puschased Amount"
from customer 
where shipping_type in ('Express','Standard')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status, 
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as Avarage_purchased_amount,
round(sum(purchase_amount),2) as Total_revenue
from customer 
group by subscription_status
order by Total_revenue , Avarage_purchased_amount desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
ROUND(100*sum(case when discount_applied = 'Yes' THEN 1 Else 0 END)/COUNT(*),2) as discount_rate
from customer
Group By item_purchased
order by discount_rate desc
LIMIT 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as(
select customer_id , previous_purchases ,
CASE 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	END as customer_segment
from customer
)

select customer_segment ,
Count (*)
from customer_type
group by customer_segment
order by count(*) desc;
--Q8. What are the top 3 most purchased products within each category? 

with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category , item_purchased
)

select item_rank, category , item_purchased ,total_orders 
from item_counts
where item_rank <= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id)
from customer
where previous_purchases >= 5
group by subscription_status


--Q10. What is the revenue contribution of each age group? 

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;